spring:
  #druid------------------------------------------------------------------
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sdjubbs?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 15773272279wt..A
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/admin/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/admin/druid/*"
        login-username: root
        login-password: 15773272279wt..A

  #redis------------------------------------------------------------------
  redis:
    host: localhost
    port: 6379
    password: 15773272279wt..A
    timeout: 5000
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3
    database: 0


#mybatis------------------------------------------------------------------
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.selenium.sdjubbs.common.bean
  configuration:
    map-underscore-to-camel-case: true

#Setting
sdjubbs:
  base-dir-save-path: /src/main/resources/static/common/
  verify-code-save-path: ${base-dir-save-path}images/verifycode
  verify-code-request-path: /common/images/verifycode
  avatar-save-path:  ${base-dir-save-path}images/avatar
  article-image-save-path: ${base-dir-save-path}images/article




